#!/bin/bash

tob=/usr/local/bin/tob
self=.

error () {
    echo "$TOB_object.$TOB_method error: $*" >&2
    exit 1
    }

# search for properties @tag, @units, @type, use first found:
unset tag
unset units
unset type
for p in ${TOB_search_paths//:/ }; do
    test -e $p/@tag && test -z "$tag" && tag=( $(<$p/@tag) )
    test -e $p/@units && test -z "$units" && units=( $(<$p/@units) )
    test -e $p/@type && test -z "$type" && type=( $(<$p/@type) )
done

# col will be the selected columns for output, if set:
unset col
unset no_header
while test -n "$1"; do
    case "$1" in
        --no-header)
            no_header=--no-header
            ;;
        --no-hdr)
            no_header=--no-header
            ;;
        --col)
            shift
            col=( ${col[@]} ${1//,/ } )
            ;;
        --column)
            shift
            col=( ${col[@]} ${1//,/ } )
            ;;
        --tag)
            shift
            for s in ${1//,/ }; do
                i=1
                for t in "${tag[@]}"; do
                    test $s == $t && {
                        col[${#col[@]}]=$i
                        break
                        }
                    i=$(($i+1))
                    unset t
                done
                test -n "$t" ||
                    error no tag $s
            done
            ;;
        *)
            break
            ;;
    esac
    shift
done

if test -n "$col"; then
    cols="${col[@]}"
    cols=(--columns ${cols// /,})
    for n in "${col[@]}"; do
        test -n "${tag[$n-1]}" || error no tag for column $n
        hdr[${#hdr[@]}]=${tag[$n-1]}  
    done
    hdr=(--header "${hdr[*]}")
fi

test -z "$hdr" && {
    hdr=(--header "${tag[*]}")
    }

echo $tob $self.super.get "${cols[@]}" "${hdr[@]}" "$@"

$tob $self.super.get "${hdr[@]}" $no_header "$@"

exit

NAME
    DataSite/TimeSeries-Data.get -- superclasses TimeSeries.get

SYNOPSIS
    ob.get [--no-hdr|no-header] [--col|column NUM]] [--tag STRING] ARGS

DESCRIPTION
    Resolves properties @tag, @units, @type, and uses them to set the
    --header option to TimeSeries.get.

    Environment variable header will be used in lieu of the above, if set.

OPTIONS
    These options must precede any options intended for the superclass 
    TimeSeries.get method.

    --no-hdr
    --no-header
    suppress header output

    --col NUM
    --column NUM
    select only identified column(s) for output
    the first column is number 1
    NUM can be a number or comma-separated list

    --tag STRING
    resolve STRING to column number per @tag property
    STRING can be a single tagname or a comma-separated list

SEE ALSO
    TimeSeries.get --help

AUTHOR
    (c) Ken.Irving@alaska.edu 2010

